In [1]:
import numpy as np
from lsst.sims.featureScheduler.modelObservatory import Model_observatory
from lsst.sims.featureScheduler.utils import empty_observation
import healpy as hp
import matplotlib.pylab as plt

In [2]:
observatory = Model_observatory()

In [16]:
def make_obs():
    obs = empty_observation()
    obs['dec'] = np.radians(-60)
    obs['RA'] = np.radians(300.)
    obs['filter'] = 'r'
    obs['rotSkyPos'] = np.radians(10.)
    return obs

In [17]:
cond1 = observatory.return_conditions()
ack = observatory.observe(make_obs())


/Users/yoachim/gitRepos/sims_featureScheduler/python/lsst/sims/featureScheduler/modelObservatory/model_observatory.py:475: RuntimeWarning: invalid value encountered in less
  slewtimes[np.where(slewtimes < 0)] = np.nan
/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:127: RuntimeWarning: divide by zero encountered in true_divide
  dCm -= 1.25 * np.log10(1 + (10**(0.8 * m5_flat_sed.dCm_infinity[visitFilter]) - 1) / Tscale)
/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:130: RuntimeWarning: divide by zero encountered in log10
  1.25 * np.log10(expTime / 30.0) - m5_flat_sed.kAtm[visitFilter] * (airmass - 1.0) - 1.1 * tauCloud)


In [18]:
ack[0]['slewtime']

array([ 120.])

In [19]:
# Let's slew to a position, swap filters. all with same rot tel pos
obs= make_obs()
obs['filter'] = 'r'
obs1 = observatory.observe(obs)
obs= make_obs()
obs['filter'] = 'g'
obs2 = observatory.observe(obs)

/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:127: RuntimeWarning: divide by zero encountered in true_divide
  dCm -= 1.25 * np.log10(1 + (10**(0.8 * m5_flat_sed.dCm_infinity[visitFilter]) - 1) / Tscale)
/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:130: RuntimeWarning: divide by zero encountered in log10
  1.25 * np.log10(expTime / 30.0) - m5_flat_sed.kAtm[visitFilter] * (airmass - 1.0) - 1.1 * tauCloud)


In [23]:
obs2[0]['slewtime'], obs1[0]['slewtime']

(array([ 120.]), array([ 2.]))

In [24]:
# Now to spin the rotator a bunch
obs= make_obs()
obs['rotSkyPos'] = np.radians(20)
obs['filter'] = 'r'
obs1 = observatory.observe(obs)
obs= make_obs()
obs['rotSkyPos'] = np.radians(-20)
obs['filter'] = 'g'
obs2 = observatory.observe(obs)

/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:127: RuntimeWarning: divide by zero encountered in true_divide
  dCm -= 1.25 * np.log10(1 + (10**(0.8 * m5_flat_sed.dCm_infinity[visitFilter]) - 1) / Tscale)
/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:130: RuntimeWarning: divide by zero encountered in log10
  1.25 * np.log10(expTime / 30.0) - m5_flat_sed.kAtm[visitFilter] * (airmass - 1.0) - 1.1 * tauCloud)


In [25]:
obs2[0]['slewtime'], obs1[0]['slewtime']

(array([ 120.]), array([ 120.]))

In [26]:
# yeah, there's clearly no rotation being taken into account.

# Now to spin the rotator a bunch
obs= make_obs()
obs['rotSkyPos'] = np.radians(20)
obs['filter'] = 'g'
obs1 = observatory.observe(obs)
obs= make_obs()
obs['rotSkyPos'] = np.radians(-20)
obs['filter'] = 'g'
obs2 = observatory.observe(obs)

/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:127: RuntimeWarning: divide by zero encountered in true_divide
  dCm -= 1.25 * np.log10(1 + (10**(0.8 * m5_flat_sed.dCm_infinity[visitFilter]) - 1) / Tscale)
/Users/yoachim/gitRepos/sims_utils/python/lsst/sims/utils/m5_flat_sed.py:130: RuntimeWarning: divide by zero encountered in log10
  1.25 * np.log10(expTime / 30.0) - m5_flat_sed.kAtm[visitFilter] * (airmass - 1.0) - 1.1 * tauCloud)


In [27]:
obs2[0]['slewtime'], obs1[0]['slewtime']

(array([ 14.92857146]), array([ 14.92857146]))

In [28]:
# ok, only takes 15s to rotate 40 degrees, so that's not too bad.